/*
@ 상품 카테고리·상품 시드 데이터
- 코드잇이 제공한 공식 시드를 우리 스키마(Category 한 테이블 + parentId)에 맞게 옮긴 것이다.
- 대분류 id는 피그마 사이드바 순서(1~7), 소분류 id는 공식 id + 100으로 고정한다.
  프론트가 카테고리를 상수로 들고 있어서 id가 바뀌면 화면이 깨진다. 임의로 바꾸지 않는다.
- 공식 시드에 없는 '원두커피'는 피그마에 있어 대분류로 추가하고,
  공식 '커피/차류'(141)를 그 아래로 옮겼다.
*/

export type SeedCategory = {
  id: number;
  name: string;
  parentId: number | null;
};

export type SeedProduct = {
  name: string;
  price: number;
  productUrl: string;
  /** 소분류 id */
  categoryId: number;
  /** 프론트 public 폴더의 상품 사진. 사진이 없는 상품은 null */
  imageUrl: string | null;
};

export const SEED_CATEGORIES: SeedCategory[] = [
  { id: 1, name: '스낵', parentId: null },
  { id: 2, name: '음료', parentId: null },
  { id: 3, name: '생수', parentId: null },
  { id: 4, name: '간편식', parentId: null },
  { id: 5, name: '신선식', parentId: null },
  { id: 6, name: '원두커피', parentId: null },
  { id: 7, name: '비품', parentId: null },

  { id: 101, name: '과자', parentId: 1 },
  { id: 102, name: '쿠키', parentId: 1 },
  { id: 103, name: '파이', parentId: 1 },
  { id: 104, name: '초콜릿류', parentId: 1 },
  { id: 105, name: '캔디류', parentId: 1 },
  { id: 106, name: '껌류', parentId: 1 },
  { id: 107, name: '비스켓류', parentId: 1 },
  { id: 108, name: '씨리얼바', parentId: 1 },
  { id: 109, name: '젤리류', parentId: 1 },
  { id: 110, name: '견과류', parentId: 1 },
  { id: 111, name: '워터젤리', parentId: 1 },
  { id: 112, name: '청량/탄산음료', parentId: 2 },
  { id: 113, name: '과즙음료', parentId: 2 },
  { id: 114, name: '에너지음료', parentId: 2 },
  { id: 115, name: '이온음료', parentId: 2 },
  { id: 116, name: '유산균음료', parentId: 2 },
  { id: 117, name: '건강음료', parentId: 2 },
  { id: 118, name: '차류', parentId: 2 },
  { id: 119, name: '두유/우유', parentId: 2 },
  { id: 120, name: '커피', parentId: 2 },
  { id: 121, name: '생수', parentId: 3 },
  { id: 122, name: '스파클링', parentId: 3 },
  { id: 123, name: '봉지라면', parentId: 4 },
  { id: 124, name: '과일', parentId: 4 },
  { id: 125, name: '컵라면', parentId: 4 },
  { id: 126, name: '핫도그 및 소시지', parentId: 4 },
  { id: 127, name: '계란', parentId: 4 },
  { id: 128, name: '죽/스프류', parentId: 4 },
  { id: 129, name: '컵밥류', parentId: 4 },
  { id: 130, name: '시리얼', parentId: 4 },
  { id: 131, name: '반찬류', parentId: 4 },
  { id: 132, name: '면류', parentId: 4 },
  { id: 133, name: '요거트류', parentId: 4 },
  { id: 134, name: '가공안주류', parentId: 4 },
  { id: 135, name: '유제품', parentId: 4 },
  { id: 136, name: '샐러드', parentId: 5 },
  { id: 137, name: '빵', parentId: 5 },
  { id: 138, name: '햄버거/샌드위치', parentId: 5 },
  { id: 139, name: '주먹밥/김밥', parentId: 5 },
  { id: 140, name: '도시락', parentId: 5 },
  { id: 141, name: '커피믹스', parentId: 6 },
  { id: 145, name: '원두', parentId: 6 },
  { id: 146, name: '캡슐커피', parentId: 6 },
  { id: 147, name: '드립백', parentId: 6 },
  { id: 142, name: '생활용품', parentId: 7 },
  { id: 143, name: '일회용품', parentId: 7 },
  { id: 144, name: '사무용품', parentId: 7 },
];

// 공식 시드 상품 61개. 이미지는 S3에 올린 뒤 채운다.
export const SEED_PRODUCTS: SeedProduct[] = [
  {
    name: '오리온 초코파이',
    price: 4000,
    productUrl: 'https://example.com/products/1001',
    categoryId: 103,
    imageUrl: '/images/products/01.webp',
  },
  {
    name: '롯데 마가렛트',
    price: 3500,
    productUrl: 'https://example.com/products/1002',
    categoryId: 102,
    imageUrl: '/images/products/02.webp',
  },
  {
    name: '농심 새우깡',
    price: 1800,
    productUrl: 'https://example.com/products/1003',
    categoryId: 101,
    imageUrl: '/images/products/03.webp',
  },
  {
    name: '해태 홈런볼',
    price: 2000,
    productUrl: 'https://example.com/products/1004',
    categoryId: 101,
    imageUrl: '/images/products/04.webp',
  },
  {
    name: '오리온 포카칩',
    price: 2200,
    productUrl: 'https://example.com/products/1005',
    categoryId: 101,
    imageUrl: '/images/products/05.webp',
  },
  {
    name: '롯데 칸쵸',
    price: 1500,
    productUrl: 'https://example.com/products/1006',
    categoryId: 102,
    imageUrl: '/images/products/06.webp',
  },
  {
    name: '크라운 산도',
    price: 1700,
    productUrl: 'https://example.com/products/1007',
    categoryId: 102,
    imageUrl: '/images/products/07.webp',
  },
  {
    name: '페레로로쉐',
    price: 3500,
    productUrl: 'https://example.com/products/1008',
    categoryId: 104,
    imageUrl: '/images/products/08.webp',
  },
  {
    name: '해태 후렌치파이',
    price: 2000,
    productUrl: 'https://example.com/products/1009',
    categoryId: 103,
    imageUrl: '/images/products/09.webp',
  },
  {
    name: '오리온 고래밥',
    price: 1800,
    productUrl: 'https://example.com/products/1010',
    categoryId: 101,
    imageUrl: '/images/products/10.webp',
  },
  {
    name: '롯데 자일리톨껌',
    price: 1200,
    productUrl: 'https://example.com/products/1011',
    categoryId: 106,
    imageUrl: '/images/products/11.webp',
  },
  {
    name: '크라운 뽀또',
    price: 1700,
    productUrl: 'https://example.com/products/1012',
    categoryId: 107,
    imageUrl: '/images/products/12.webp',
  },
  {
    name: '오리온 닥터유 단백질바',
    price: 2500,
    productUrl: 'https://example.com/products/1013',
    categoryId: 108,
    imageUrl: '/images/products/13.webp',
  },
  {
    name: '청우 젤리스트로베리',
    price: 1200,
    productUrl: 'https://example.com/products/1014',
    categoryId: 109,
    imageUrl: '/images/products/14.webp',
  },
  {
    name: '오리온 오감자',
    price: 2000,
    productUrl: 'https://example.com/products/1015',
    categoryId: 101,
    imageUrl: '/images/products/15.webp',
  },
  {
    name: '코카콜라 500ml',
    price: 2200,
    productUrl: 'https://example.com/products/2001',
    categoryId: 112,
    imageUrl: '/images/products/16.webp',
  },
  {
    name: '펩시콜라 500ml',
    price: 2000,
    productUrl: 'https://example.com/products/2002',
    categoryId: 112,
    imageUrl: '/images/products/17.webp',
  },
  {
    name: '칠성사이다 500ml',
    price: 2000,
    productUrl: 'https://example.com/products/2003',
    categoryId: 112,
    imageUrl: '/images/products/18.webp',
  },
  {
    name: '트로피카나 스파클링',
    price: 1800,
    productUrl: 'https://example.com/products/2004',
    categoryId: 112,
    imageUrl: '/images/products/19.webp',
  },
  {
    name: '델몬트 오렌지주스',
    price: 2500,
    productUrl: 'https://example.com/products/2005',
    categoryId: 113,
    imageUrl: '/images/products/20.webp',
  },
  {
    name: '썬키스트 포도주스',
    price: 2500,
    productUrl: 'https://example.com/products/2006',
    categoryId: 113,
    imageUrl: '/images/products/21.webp',
  },
  {
    name: '레드불',
    price: 3500,
    productUrl: 'https://example.com/products/2007',
    categoryId: 114,
    imageUrl: '/images/products/22.webp',
  },
  {
    name: '핫식스',
    price: 2000,
    productUrl: 'https://example.com/products/2008',
    categoryId: 114,
    imageUrl: '/images/products/23.webp',
  },
  {
    name: '포카리스웨트',
    price: 1800,
    productUrl: 'https://example.com/products/2009',
    categoryId: 115,
    imageUrl: '/images/products/24.webp',
  },
  {
    name: '게토레이',
    price: 1800,
    productUrl: 'https://example.com/products/2010',
    categoryId: 115,
    imageUrl: '/images/products/25.webp',
  },
  {
    name: '야쿠르트',
    price: 1200,
    productUrl: 'https://example.com/products/2011',
    categoryId: 116,
    imageUrl: '/images/products/26.webp',
  },
  {
    name: '헛개수',
    price: 2000,
    productUrl: 'https://example.com/products/2012',
    categoryId: 117,
    imageUrl: '/images/products/27.webp',
  },
  {
    name: '녹차 500ml',
    price: 1500,
    productUrl: 'https://example.com/products/2013',
    categoryId: 118,
    imageUrl: '/images/products/28.webp',
  },
  {
    name: '서울우유 흰우유 200ml',
    price: 1500,
    productUrl: 'https://example.com/products/2014',
    categoryId: 119,
    imageUrl: '/images/products/29.webp',
  },
  {
    name: '매일 두유',
    price: 1800,
    productUrl: 'https://example.com/products/2015',
    categoryId: 119,
    imageUrl: '/images/products/30.webp',
  },
  {
    name: '맥심TOP 캔커피',
    price: 2000,
    productUrl: 'https://example.com/products/2016',
    categoryId: 120,
    imageUrl: '/images/products/31.webp',
  },
  {
    name: '삼다수 500ml',
    price: 1200,
    productUrl: 'https://example.com/products/3001',
    categoryId: 121,
    imageUrl: '/images/products/32.webp',
  },
  {
    name: '아이시스 8.0 500ml',
    price: 1100,
    productUrl: 'https://example.com/products/3002',
    categoryId: 121,
    imageUrl: '/images/products/33.webp',
  },
  {
    name: '에비앙 500ml',
    price: 2500,
    productUrl: 'https://example.com/products/3003',
    categoryId: 121,
    imageUrl: '/images/products/34.webp',
  },
  {
    name: '트레비 레몬 500ml',
    price: 1700,
    productUrl: 'https://example.com/products/3004',
    categoryId: 122,
    imageUrl: '/images/products/35.webp',
  },
  {
    name: '씨그램 플레인 500ml',
    price: 1600,
    productUrl: 'https://example.com/products/3005',
    categoryId: 122,
    imageUrl: '/images/products/36.webp',
  },
  {
    name: '백산수 500ml',
    price: 1200,
    productUrl: 'https://example.com/products/3006',
    categoryId: 121,
    imageUrl: '/images/products/37.webp',
  },
  {
    name: '동원샘물 500ml',
    price: 1000,
    productUrl: 'https://example.com/products/3007',
    categoryId: 121,
    imageUrl: '/images/products/38.webp',
  },
  {
    name: '농심 신라면',
    price: 1200,
    productUrl: 'https://example.com/products/4001',
    categoryId: 123,
    imageUrl: '/images/products/39.webp',
  },
  {
    name: '삼양 불닭볶음면',
    price: 1500,
    productUrl: 'https://example.com/products/4002',
    categoryId: 132,
    imageUrl: '/images/products/40.webp',
  },
  {
    name: '오뚜기 진라면',
    price: 1200,
    productUrl: 'https://example.com/products/4003',
    categoryId: 123,
    imageUrl: '/images/products/41.webp',
  },
  {
    name: '팔도 비빔면',
    price: 1300,
    productUrl: 'https://example.com/products/4004',
    categoryId: 132,
    imageUrl: '/images/products/42.webp',
  },
  {
    name: '오뚜기 컵누들',
    price: 1200,
    productUrl: 'https://example.com/products/4005',
    categoryId: 125,
    imageUrl: '/images/products/43.webp',
  },
  {
    name: 'CJ 햇반 컵밥',
    price: 3500,
    productUrl: 'https://example.com/products/4006',
    categoryId: 129,
    imageUrl: null,
  },
  {
    name: '서울우유 요거트',
    price: 1800,
    productUrl: 'https://example.com/products/4007',
    categoryId: 133,
    imageUrl: '/images/products/45.webp',
  },
  {
    name: '풀무원 전복죽',
    price: 3500,
    productUrl: 'https://example.com/products/4008',
    categoryId: 128,
    imageUrl: '/images/products/46.webp',
  },
  {
    name: 'CJ 비비고 계란찜',
    price: 2500,
    productUrl: 'https://example.com/products/4009',
    categoryId: 127,
    imageUrl: '/images/products/47.webp',
  },
  {
    name: '서울우유 스트링치즈',
    price: 2000,
    productUrl: 'https://example.com/products/4010',
    categoryId: 135,
    imageUrl: '/images/products/48.webp',
  },
  {
    name: '풀무원 샐러드',
    price: 4000,
    productUrl: 'https://example.com/products/5001',
    categoryId: 136,
    imageUrl: '/images/products/49.webp',
  },
  {
    name: '파리바게뜨 소금빵',
    price: 2500,
    productUrl: 'https://example.com/products/5002',
    categoryId: 137,
    imageUrl: '/images/products/50.webp',
  },
  {
    name: '파리바게뜨 크림빵',
    price: 2500,
    productUrl: 'https://example.com/products/5003',
    categoryId: 137,
    imageUrl: '/images/products/51.webp',
  },
  {
    name: '파리바게뜨 햄치즈샌드위치',
    price: 3500,
    productUrl: 'https://example.com/products/5004',
    categoryId: 138,
    imageUrl: '/images/products/52.webp',
  },
  {
    name: 'GS25 참치마요 주먹밥',
    price: 1800,
    productUrl: 'https://example.com/products/5005',
    categoryId: 139,
    imageUrl: '/images/products/53.webp',
  },
  {
    name: 'CU 불고기김밥',
    price: 2500,
    productUrl: 'https://example.com/products/5006',
    categoryId: 139,
    imageUrl: '/images/products/54.webp',
  },
  {
    name: 'GS25 제육도시락',
    price: 4500,
    productUrl: 'https://example.com/products/5007',
    categoryId: 140,
    imageUrl: '/images/products/55.webp',
  },
  {
    name: '맥심 모카골드 커피믹스',
    price: 12000,
    productUrl: 'https://example.com/products/6001',
    categoryId: 141,
    imageUrl: '/images/products/56.webp',
  },
  {
    name: '도루코 면도기',
    price: 5000,
    productUrl: 'https://example.com/products/6002',
    categoryId: 142,
    imageUrl: '/images/products/57.webp',
  },
  {
    name: '크리넥스 미용티슈',
    price: 3500,
    productUrl: 'https://example.com/products/6003',
    categoryId: 142,
    imageUrl: '/images/products/58.webp',
  },
  {
    name: '일회용 종이컵',
    price: 2000,
    productUrl: 'https://example.com/products/6004',
    categoryId: 143,
    imageUrl: '/images/products/59.webp',
  },
  {
    name: '모나미 볼펜',
    price: 1000,
    productUrl: 'https://example.com/products/6005',
    categoryId: 144,
    imageUrl: '/images/products/60.webp',
  },
  {
    name: '3M 포스트잇',
    price: 2500,
    productUrl: 'https://example.com/products/6006',
    categoryId: 144,
    imageUrl: '/images/products/61.webp',
  },
];
