name: Deploy To EC2

on:
  push:
    branches:
      - chore/cicd # CI/CD 구축 완료 후 main으로 변경

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 깃헙 레포지토리 불러오기
        uses: actions/checkout@v4

      - name: Node 버전 고정
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Production 환경변수 파일 생성
        env:
          ENV_FILE: ${{ secrets.ENV }}
        run: |
          printf '%s' "$ENV_FILE" > .env

      - name: 의존성 설치
        run: npm ci

      - name: 테스트 코드 실행
        run: npm run test

      - name: TypeScript 빌드
        run: npm run build

      - name: 배포 파일 압축
        run: |
          tar -czvf project.tar.gz \
            dist \
            prisma \
            prisma7.config.ts \
            .env \
            package.json \
            package-lock.json
